// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $Portal_layout from "./routes/Portal/_layout.tsx";
import * as $Portal_index from "./routes/Portal/index.tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $login from "./routes/login.tsx";
import * as $buttons_Logout from "./islands/buttons/Logout.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/Portal/_layout.tsx": $Portal_layout,
    "./routes/Portal/index.tsx": $Portal_index,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/login.tsx": $login,
  },
  islands: {
    "./islands/buttons/Logout.tsx": $buttons_Logout,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
