// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $Clientes_id_ from "./routes/Clientes/[id].tsx";
import * as $Clientes_index from "./routes/Clientes/index.tsx";
import * as $Empresas_id_ from "./routes/Empresas/[id].tsx";
import * as $Empresas_index from "./routes/Empresas/index.tsx";
import * as $Portal_index from "./routes/Portal/index.tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $login from "./routes/login.tsx";
import * as $Desplegables_Toolbar_Articulo from "./islands/Desplegables/Toolbar_Articulo.tsx";
import * as $Desplegables_Toolbar_Cliente from "./islands/Desplegables/Toolbar_Cliente.tsx";
import * as $Desplegables_Toolbar_Otros from "./islands/Desplegables/Toolbar_Otros.tsx";
import * as $Desplegables_Toolbar_Pedidos from "./islands/Desplegables/Toolbar_Pedidos.tsx";
import * as $buttons_Logout from "./islands/buttons/Logout.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/Clientes/[id].tsx": $Clientes_id_,
    "./routes/Clientes/index.tsx": $Clientes_index,
    "./routes/Empresas/[id].tsx": $Empresas_id_,
    "./routes/Empresas/index.tsx": $Empresas_index,
    "./routes/Portal/index.tsx": $Portal_index,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/_middleware.ts": $_middleware,
    "./routes/login.tsx": $login,
  },
  islands: {
    "./islands/Desplegables/Toolbar_Articulo.tsx":
      $Desplegables_Toolbar_Articulo,
    "./islands/Desplegables/Toolbar_Cliente.tsx": $Desplegables_Toolbar_Cliente,
    "./islands/Desplegables/Toolbar_Otros.tsx": $Desplegables_Toolbar_Otros,
    "./islands/Desplegables/Toolbar_Pedidos.tsx": $Desplegables_Toolbar_Pedidos,
    "./islands/buttons/Logout.tsx": $buttons_Logout,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
